name: GitHub Actions deploy hasura migrate apply
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      hasura:
        image: hasura/graphql-engine:latest
        env:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
        ports:
          - 8080:8080
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: install hasura cli
        run: curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
      - name: create config.yaml
        run: touch config.yaml | cd hasura
      - name: show current path
        run:  echo `pwd`
      - name: show current files
        run:  echo `ls -l`
      - name: restore data
        run:  hasura migrate apply --endpoint http://localhost:8080
 
 
